name: ci

on:
  push:
    branches:
      - main
    paths:
      - 'environment.yml'
      - 'files/'
      - 'poetry.lock'
      - 'jupyter_lite_config.json'
      - 'copy.sh'
  pull_request:
    branches:
      - '*'
    paths:
      - 'environment.yml'
      - 'files/'
      - 'poetry.lock'
      - 'jupyter_lite_config.json'
      - 'copy.sh'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: snok/install-poetry@v1.3.3
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Cache venv
        id: cached-pip-wheels
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: venv-${{ hashFiles('**/poetry.lock') }}
      - name: Install Python dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Copy to-be-included files
        run: |
          bash copy.sh
      - name: Build
        shell: bash -l {0}
        run: |
          poetry run jupyter lite build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./_output/
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
